# Stage 1: Build
FROM node:22-alpine AS build-stage
WORKDIR /app
# We reference the path from the project root
COPY src/frontend/package*.json ./
RUN npm install
COPY src/frontend/ ./
RUN npm run build

# Stage 2: Production
FROM nginx:stable-alpine AS production-stage
ENV FRONTEND_BACKEND_ORIGIN=http://backend:8000
COPY docker/nginx.frontend.conf /etc/nginx/templates/default.conf.template
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
