"""create collected_samples table

Revision ID: 5c3180f8767a
Revises: cea8f95f3d0a
Create Date: 2026-06-08 16:01:14.143641

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "5c3180f8767a"
down_revision: Union[str, None] = "cea8f95f3d0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collected_samples",
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column(
            "user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True
        ),
        sa.Column("letter", sa.String(length=10), nullable=False),
        sa.Column("image_path", sa.String(length=500), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_collected_samples_created_at"),
        "collected_samples",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_collected_samples_letter"),
        "collected_samples",
        ["letter"],
        unique=False,
    )
    op.create_index(
        op.f("ix_collected_samples_user_id"),
        "collected_samples",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_collected_samples_user_id"), table_name="collected_samples")
    op.drop_index(op.f("ix_collected_samples_letter"), table_name="collected_samples")
    op.drop_index(
        op.f("ix_collected_samples_created_at"), table_name="collected_samples"
    )
    op.drop_table("collected_samples")
    # ### end Alembic commands ###
