"""drop letters_learned from user_stats

Revision ID: e5d8fa74a772
Revises: 43d8d76df97e
Create Date: 2026-06-09 19:32:19.439565

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e5d8fa74a772"
down_revision: Union[str, None] = "43d8d76df97e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_stats", "letters_learned")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_stats",
        sa.Column("letters_learned", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
